# Generated by Django 5.0.6 on 2024-06-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='capacity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_type',
            field=models.CharField(choices=[('train', 'Train'), ('flight', 'Flight')], max_length=10),
        ),
    ]
