# Generated by Django 5.0.6 on 2024-06-22 08:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_alter_booking_seat_number_alter_ticket_capacity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booked_on',
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unique_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
